name: 'Meeting Nopes'
description: 'Less copy pasta, more focus on the meeting!'
inputs:
  template:  # id of input
    description: 'The path to a notes template file in this repository'
    required: true
    default: 'notes/weekly-sync/template.md'
  project-column-id:
    description: 'The ID of the Project Column from which to pull issues'
    required: true
  personal-access-token:
    description: 'A Personal Access Token that can access Projects'
    required: true
  github-token:
    description: 'The secrets.GITHUB_TOKEN for this Workflow'
    required: true
outputs:
  pull-request-url: # id of output
    description: 'The URL for the meeting notes Pull Request'
runs:
  using: 'node12'
  main: 'index.js'
